### ISSUE TITLE
@ symbols being added to the end of miRNA names

### ISSUE THREAD

**Issue by kdzimm** [baohongz/QuickMIRSeq#1]
@baohongz Really like your package. Very thorough and fast for aligning and quantifying miRNAs. Thank you.

I have one problem I am encountering. At the end of some of my miRNAs, I finding some of them are getting an @ symbol appended to the end. I can't find these @ symbols in the fasta files, so I know something odd is happening, I just cannot figure out what. Any ideas where this is coming from or what the @ symbol means in this context? Is ssc-miR-199a-3p@ really just ssc-miR-199a-3p? or is ssc-miR-9@ really just ssc-miR-9? Why is the @ symbol being added on in these few instances?

**Comment by baohongz** [comment]
We mapped reads to “modified miRNA (with an extension of a couple of bases at both 5’ and 3’end”. 

If so, for those miRNAs that are potentially derived from the same miRNA precursor (but different entries in miRNA database), we cannot distinguish them for sure. Below is an example (has-mir-520c is the miRNA precursor). 
 
![image](https://user-images.githubusercontent.com/15882624/78461875-b1e77a80-769a-11ea-8257-bc8ec47394d3.png)

**Comment by kdzimm** [comment]
Perfect. Thank you! Very helpful.
